---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/template_files.yml'
  vars:
    template_files:
      - owner:          'root'
        group:          'root'
        mode:           '0640'
        src:            'templates/conf/logrotate.d/syslog_client.j2'
        dest:           "/etc/logrotate.d/syslog_client_{{ syslog_client }}"
  with_items:
    - "{{ groups['syslog-client'] }}"
    - "{{ inventory_hostname }}"
  loop_control:
    loop_var:           'syslog_client'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 template_files_result.changed
